### ISSUE TITLE
Газетный корпус: Задание подкорпуса

### ISSUE THREAD

**Issue by savsvetlana** [oopcode/nkra-saas#14]
Название *(звездочка) - не найдено
Автор * (звездочка) не срабатывает
Год публикации – не срабатывает
Источник – Известия Найдено 49 748 документов общим объемом 25 526 625 слов.
Но ср. в действующем корпусе - Найдено 49 757 документов общим объемом 2 486 641 предложение, 30 806 829 слов
Расхождения в статистике – отличаются объемы подкорпусов
Отличается кол-во словоформ в документах: 
Алексей Певчев. «Машина Времени» в загадочной сборке: 510 vs 514 в действующем корп.
Арсений Погосян 1412 vs 1423 и т.д.
Формат выдачи – нет названия газеты, дата неточная: Алексей Певчев. «Машина Времени» в загадочной сборке (2014.07) 
Ср.: Алексей Певчев. «Машина Времени» в загадочной сборке // Известия, 2014.07.24  
Количество документов – по умолчанию 10, должно быть 50 (при  попытке  установить вручную в Настройках, не срабатывают изменения)

**Comment by oopcode** [comment]
По поводу задания подкорпуса -- см. здесь и в остальных issues https://github.com/oopcode/nkra-saas/issues/24

Поиск по звездочке в авторе и названии -- поправил везде (во всех остальных issues буду игнорировать)

По поводу статистики и количества словоформ -- пока что буду игнорировать везде (не первоочередная важность)
