### ISSUE TITLE
Акцентологический корпус: задание подкопуса

### ISSUE THREAD

**Issue by savsvetlana** [oopcode/nkra-saas#21]
В целом дела обстоят хуже, чем в устном

- Название, Автор * не работают  По этому запросу ничего не найдено
Пол Мужской, женский  не работает  
Год рождения автора - не работает  
Год создания – работает

1. Поэзия
Новый: Найдено 78 854 документа общим объемом 10 923 626 слов
Старый: Найдено 78 870 документов общим объемом 1 045 916 предложений, 10 928 074 слова.
Порядок текстов в выдаче по умолчанию отличается.  
2. Устная публичная речь – не ищет
3. Устная непубличная речь – не ищет
3. Авторское чтение       Художественное чтение  не ищет
4. Театральная речь  не ищет
5. Речь кино  не ищет
Исключить из поиска "наивную поэзию"  не работает

- Полнота корпуса
Неполный, не все корпуса проиндексированы (?)

**Comment by oopcode** [comment]
Переиндексировал, он стал все искать, но выяснилась новая проблема -- кнопка “сохранить подкорпус и перейти…” работает неправильно. Разбираемся с Алексеем.

**Comment by oopcode** [comment]
Поправлено.
