### ISSUE TITLE
Пробелы при знаках препинания

### ISSUE THREAD

**Issue by dmsichinava** [oopcode/nkra-saas#25]
В выдаче ряд знаков препинания сопровождается паразитическими пробелами:
дефис между токенами (рожа-то, Кантариди-младший) -- лишний пробел после знака.
[С дефисом внутри токена типа "кому-то" или "где-нибудь" этих проблем нет]
Открывающая кавычка (« Внутреннем обозрении») -- лишний пробел после знака
Скобки -- лишние пробелы после открывающей и после закрывающей

Примеры тут
http://processing.ruscorpora.ru:8888/?sort=gr_tagging&lang=ru&lex1=%D0%BA%D1%80%D0%BE%D0%BB%D0%B8%D0%BA&text=lexgramm&max1=1&level1=0&level2=0&mode=main&parent1=0&min1=1&flags1=bques&nodia=1&parent2=0&p=3

**Comment by oopcode** [comment]
Поправил.

<img width="289" alt="screen shot 2018-06-12 at 22 43 42" src="https://user-images.githubusercontent.com/6124982/41313247-1f67219a-6e92-11e8-8de8-8bb68e4000d5.png">
