### ISSUE TITLE
Поэтический корпус: не работают семантич. признаки

### ISSUE THREAD

**Issue by nevmenandr** [oopcode/nkra-saas#5]
При поиске не учитываются семантические признаки. Находятся просто все словарные единицы данной части речи.

**Comment by oopcode** [comment]
В смысле -- не работают? Работают же.

<img width="689" alt="screen shot 2018-04-07 at 17 46 06" src="https://user-images.githubusercontent.com/6124982/38456286-bdda4888-3a8b-11e8-996c-ba51f5dad0ad.png">
<img width="735" alt="screen shot 2018-04-07 at 17 46 19" src="https://user-images.githubusercontent.com/6124982/38456287-bdfed464-3a8b-11e8-8e61-5cab38c21ca3.png">

Я думаю, дело в том, что там почему-то при выборе семантики прописываются еще и грамматические признаки.

**Comment by nevmenandr** [comment]
Да, теперь работают.
