### ISSUE TITLE
Поэтический корпус: задать подкорпус: точное вхождение

### ISSUE THREAD

**Issue by olesar** [oopcode/nkra-saas#6]
При нажатой галке выдаются тексты подкорпуса, выходящие за рамки указанного периода.
Пример: Выдается Радищев текст 1797-1800 на запрос 1800-2018 (точное вхождение)
http://search1.ruscorpora.ru/search.xml?env=alpha&text=meta&mode=poetic&sort=gr_tagging&lang=ru&doc_te_header=&doc_t_cyclus=&doc_t_liber=&doc_te_author=&doc_sex=&doc_g_birthday=&doc_l_birthday=&doc_te_original=&doc_g_created=1800&doc_l_created=2018&exact=-%ED%E5%F2%EE%F7%ED%E0%FF&doc_location=&doc_location_normalized=&doc_g_verses=&doc_l_verses=&doc_genre_fi=&doc_language=&doc_meter=&doc_feet=&doc_clausula=&doc_strophe=&doc_gr_strophe=&doc_rhyme=&doc_formula=&doc_extra=&doc_g_crevision=&doc_l_crevision=&p=1517

**Comment by oopcode** [comment]
Запрос работает по принципу "включительно", это поведение предусмотрено. Если ввести 1801-2018, то эти тексты уходят из выдачи.

**Comment by olesar** [comment]
Но тогда, что есть галка, что ее нет, выдача работает одинаково? Если ввести 1801-2018,  они и без галки уйдут из выдачи.
Полагаю, что там дырка в логике, например, исключаются тексты только по верхней дате, но не по нижней, разберитесь.
